name: 'ec2 unity machine pool'
description: 'This is a GitHub Action that creates a machine pool of EC2 instances for Unity builds.'
author: 'Nisan'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  aws-access-key-id:
    description: 'aws access key id with permissions to create ec2 instances and the state resources'
    required: true
  aws-secret-access-key:
    description: 'aws secret access key with permissions to create ec2 instances and the state resources'
    required: true
  aws-region:
    description: 'region for aws state resource'
    required: true
  aws-machine-bucket:
    description: 'aws s3 bucket name for machine allocator state'
    required: true
  aws-dynamodb-table:
    description: 'aws dynamodb table name for machine allocator state'
    required: true

  allocate-machine:
    description: 'allocate / return machine'
    required: true

  allocation_id:
    description: 'allocation id'
    required: false

outputs:
  allocation_id:
    description: 'allocation id for the new allocation / the allocation that was returned'
  instance_id:
    description: 'instance id for the new instance / the instance that was returned'
  instance_name:
    description: 'instance name for the new instance / the instance that was returned'
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node20'
  main: 'dist/index.js'
