@echo off

call %~dp0set-dotenv.bat

@REM Print environment variables

echo NODE_ENV="%NODE_ENV%"
echo AWS_ACCOUNT_NAME="%AWS_ACCOUNT_NAME%"
echo AWS_ACCESS_KEY_ID="%AWS_ACCESS_KEY_ID%"
echo AWS_SECRET_ACCESS_KEY="%AWS_SECRET_ACCESS_KEY%"
echo AWS_BUCKET="%AWS_BUCKET%"
echo AWS_DYNAMODB_TABLE="%AWS_DYNAMODB_TABLE%"
echo AWS_REGION="%AWS_REGION%"
echo ALLOCATE_MACHINE="%ALLOCATE_MACHINE%"
echo ALLOCATION_ID="%ALLOCATION_ID%"